services:
    application-api:
        container_name: application-api
        build:
            context: ./application-api
            dockerfile: Dockerfile
        ports:
            - "3000:3000"

    application-web:
        container_name: application-web
        build:
            context: ./application-web
            dockerfile: Dockerfile
        ports:
            - "8080:80"